name: RSYNC Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main # or the branch you want to use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
        run: ssh-keyscan $SFTP_SERVER >> ~/.ssh/known_hosts

      - name: Rsync deploy
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_TARGET_DIR: ${{ secrets.SFTP_TARGET_DIR }}
        run: |
          rsync -avz --delete -e "ssh" src/ $SFTP_USERNAME@$SFTP_SERVER:$SFTP_TARGET_DIR
